add database to docker-compose, create dockerignore
sangvinij/authorization pull request #7
Opened 2023-05-08 15:47 UTC by sangvinij

2023-05-09 15:03 UTC, alexander-sidorov requested changes

2023-05-09 15:03 UTC, alexander-sidorov commented on entrypoint.sh
> +sleep 30
зачем????

если хотите, чтобы сервис webapp дождался базы, то вот [пример](https://github.com/alexander-sidorov/m-pt1-63-23/blob/0a61ad0149643115ca719ecdcbedaba13ac339bb/docker-compose.yml#L54):

```yml
  webapp:
    depends_on:
      db:
        condition: service_healthy
```

тем более что у сервиса базы есть хэлсчек статус

2023-05-09 15:03 UTC, alexander-sidorov commented on pyproject.toml
> +psycopg = "^3.1.9"
`psycopg` вам не нужен

2023-05-09 15:03 UTC, alexander-sidorov commented on pyproject.toml
> +psycopg2 = "^2.9.6"
вместо `psycopg2` пожалуйста, используйте `psycopg2-binary`, чтобы не зависеть от библиотек уровня компиляции

2023-05-09 15:03 UTC, alexander-sidorov commented on docker-compose.yml
> +    healthcheck:
а в составе самого образа `postgres` нету healthcheck?

2023-05-10 10:21 UTC, sangvinij commented
1. Классы UserCreationForm и UserChangeForm перемещены из accounts/admin.py в accounts/forms.py
2. Модель User зарегистрирована в админ-панели с помощью декоратора
3. Django теперь получает URL-ссылку на базу данных из переменной окружения
4. Изменены названия docker-контейнеров, определены версии образов
5. Сервис `webapp` теперь зависит от health-статуса сервиса `db`
6. `psycopg` и `psycopg2`заменены на `psycopg2-binary`
7. создана папка **.local**, в которой будут находиться локальные файлы проекта
8. Добавлены настройки для `flake8`. Теперь можно запустить из корня проекта команду `pflake8 .`, чтобы проверить код на отсутствие стилистических ошибок и соответствие pep8

2023-05-12 08:46 UTC, merged